// @celsian/cli — Deploy command: generates config files and deploys to platform CLIs

import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { logger } from "../utils/logger.js";

export type DeployTarget = "vercel" | "lambda" | "cloudflare" | "fly" | "railway" | "docker";

const VALID_TARGETS: DeployTarget[] = ["vercel", "lambda", "cloudflare", "fly", "railway", "docker"];

// -- Auto-detection from existing config files ----------------------------------

const CONFIG_DETECTION: Array<[string, DeployTarget]> = [
  ["wrangler.toml", "cloudflare"],
  ["fly.toml", "fly"],
  ["vercel.json", "vercel"],
  ["railway.json", "railway"],
  ["template.yaml", "lambda"],
];

function autoDetectPlatform(): DeployTarget | null {
  const cwd = process.cwd();
  for (const [file, target] of CONFIG_DETECTION) {
    if (existsSync(resolve(cwd, file))) {
      return target;
    }
  }
  return null;
}

// -- CLI tool availability check -----------------------------------------------

function isCliAvailable(command: string): boolean {
  try {
    execSync(command, { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

// -- File templates per target --------------------------------------------------

const VERCEL_INDEX = `// Generated by: celsian deploy --target vercel
// Adjust the import path below to match your app's entry point.

import { createVercelHandler } from "@celsian/adapter-vercel";
import { createApp } from "@celsian/core";

const app = createApp();

// TODO: Import your routes here, or move your app setup to a shared module:
// import { setupRoutes } from "../src/routes.js";
// setupRoutes(app);

app.get("/api/health", (_req, reply) => reply.json({ status: "ok" }));

await app.ready();

export default createVercelHandler(app);
`;

const VERCEL_JSON = `{
  "rewrites": [
    { "source": "/api/(.*)", "destination": "/api" }
  ]
}
`;

const LAMBDA_HANDLER = `// Generated by: celsian deploy --target lambda
// Adjust the import path below to match your app's entry point.

import { createLambdaHandler } from "@celsian/adapter-lambda";
import { createApp } from "@celsian/core";

const app = createApp({ trustProxy: true });

// TODO: Import your routes here
app.get("/health", (_req, reply) => reply.json({ status: "ok" }));

await app.ready();

export const handler = createLambdaHandler(app);
`;

const LAMBDA_TEMPLATE_YAML = `AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CelsianJS API deployed via AWS SAM

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 256
    Timeout: 30

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambda.handler
      Events:
        ApiGateway:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
`;

const CLOUDFLARE_WORKER = `// Generated by: celsian deploy --target cloudflare
// Adjust the import path below to match your app's entry point.

import { createCloudflareHandler } from "@celsian/adapter-cloudflare";
import { createApp } from "@celsian/core";

const app = createApp();

// TODO: Import your routes here
app.get("/health", (_req, reply) => reply.json({ status: "ok" }));

export default createCloudflareHandler(app);
`;

const WRANGLER_TOML = `name = "my-celsian-api"
main = "worker.ts"
compatibility_date = "2024-01-01"

# Uncomment to add KV namespaces, D1 databases, etc.
# [[kv_namespaces]]
# binding = "MY_KV"
# id = ""
`;

const FLY_TOML = `app = "my-celsian-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "5s"
`;

const DOCKERFILE = `FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN \\
  if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \\
  elif [ -f package-lock.json ]; then npm ci; \\
  else npm install; fi
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN addgroup -g 1001 -S celsian && adduser -S celsian -u 1001
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
USER celsian
EXPOSE 3000
CMD ["node", "dist/index.js"]
`;

const DOCKERIGNORE = `node_modules
dist
.git
*.md
.env*
`;

const RAILWAY_JSON = `{
  "$schema": "https://railway.com/railway.schema.json",
  "build": {
    "builder": "NIXPACKS"
  },
  "deploy": {
    "startCommand": "node dist/index.js",
    "healthcheckPath": "/health",
    "healthcheckTimeout": 300,
    "restartPolicyType": "ON_FAILURE"
  }
}
`;

const PROCFILE = `web: node dist/index.js
`;

// -- Target -> files mapping ----------------------------------------------------

export function getFilesForTarget(target: DeployTarget): Array<[string, string]> {
  switch (target) {
    case "vercel":
      return [
        ["api/index.ts", VERCEL_INDEX],
        ["vercel.json", VERCEL_JSON],
      ];
    case "lambda":
      return [
        ["lambda.ts", LAMBDA_HANDLER],
        ["template.yaml", LAMBDA_TEMPLATE_YAML],
      ];
    case "cloudflare":
      return [
        ["worker.ts", CLOUDFLARE_WORKER],
        ["wrangler.toml", WRANGLER_TOML],
      ];
    case "fly":
      return [
        ["Dockerfile", DOCKERFILE],
        ["fly.toml", FLY_TOML],
        [".dockerignore", DOCKERIGNORE],
      ];
    case "railway":
      return [
        ["Dockerfile", DOCKERFILE],
        ["railway.json", RAILWAY_JSON],
        ["Procfile", PROCFILE],
      ];
    case "docker":
      return [
        ["Dockerfile", DOCKERFILE],
        [".dockerignore", DOCKERIGNORE],
      ];
  }
}

// -- Platform CLI commands -------------------------------------------------------

interface PlatformCli {
  checkCmd: string;
  installHint: string;
  deployCmd: string;
}

const PLATFORM_CLIS: Partial<Record<DeployTarget, PlatformCli>> = {
  cloudflare: {
    checkCmd: "npx wrangler --version",
    installHint: "npm install -D wrangler",
    deployCmd: "npx wrangler deploy",
  },
  fly: {
    checkCmd: "flyctl version",
    installHint: "https://fly.io/docs/hands-on/install-flyctl/",
    deployCmd: "flyctl deploy",
  },
  lambda: {
    checkCmd: "sam --version",
    installHint: "https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html",
    deployCmd: "sam build && sam deploy --guided",
  },
  vercel: {
    checkCmd: "npx vercel --version",
    installHint: "npm install -g vercel",
    deployCmd: "npx vercel deploy",
  },
  railway: {
    checkCmd: "railway version",
    installHint: "npm install -g @railway/cli",
    deployCmd: "railway up",
  },
};

// -- Next-steps output ----------------------------------------------------------

const SERVERLESS_NOTE =
  "Note: Background tasks (app.task/app.enqueue) and cron jobs (app.cron) require a long-running server.\n      For serverless, use platform-native scheduling instead.";

function printNextSteps(target: DeployTarget, willDeploy: boolean): void {
  if (willDeploy) return; // Already deploying, no need for next-steps hints

  switch (target) {
    case "vercel":
      logger.info("Run `vercel deploy` to deploy. Adjust api/index.ts to import your routes.");
      console.log("");
      logger.dim(SERVERLESS_NOTE);
      break;
    case "lambda":
      logger.info("Run `sam build && sam deploy --guided`. Adjust lambda.ts to import your routes.");
      console.log("");
      logger.dim(SERVERLESS_NOTE);
      break;
    case "cloudflare":
      logger.info("Run `npx wrangler deploy`. Adjust worker.ts to import your routes.");
      console.log("");
      logger.dim(SERVERLESS_NOTE);
      break;
    case "fly":
      logger.info("Run `flyctl launch` then `flyctl deploy`.");
      break;
    case "railway":
      logger.info("Push to git — Railway auto-deploys. Or run `railway up`.");
      break;
    case "docker":
      logger.info("Run `docker build -t my-api .` then `docker run -p 3000:3000 my-api`.");
      break;
  }
}

// -- Main command ---------------------------------------------------------------

export async function deployCommand(targetOrNull: string | null, options?: { deploy?: boolean }): Promise<void> {
  let target = targetOrNull;

  // Auto-detect platform if not specified
  if (!target) {
    const detected = autoDetectPlatform();
    if (detected) {
      logger.info(`Auto-detected platform: ${detected}`);
      target = detected;
    } else {
      logger.error("No platform specified and none could be auto-detected.");
      logger.dim("Usage: celsian deploy --platform <vercel|lambda|cloudflare|fly|railway|docker>");
      logger.dim("Or create a config file (wrangler.toml, fly.toml, vercel.json, etc.) for auto-detection.");
      process.exit(1);
    }
  }

  if (!VALID_TARGETS.includes(target as DeployTarget)) {
    logger.error(`Unknown deploy target: "${target}". Valid targets: ${VALID_TARGETS.join(", ")}`);
    process.exit(1);
  }

  const cwd = process.cwd();
  const generated: string[] = [];
  const skipped: string[] = [];

  const files = getFilesForTarget(target as DeployTarget);

  for (const [relPath, content] of files) {
    const absPath = resolve(cwd, relPath);
    if (existsSync(absPath)) {
      skipped.push(relPath);
      continue;
    }
    const dir = dirname(absPath);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    writeFileSync(absPath, content, "utf-8");
    generated.push(relPath);
  }

  // Print results
  if (generated.length > 0) {
    logger.success(`Generated ${generated.length} file(s) for ${target}:`);
    for (const f of generated) {
      logger.dim(`  + ${f}`);
    }
  }
  if (skipped.length > 0) {
    logger.warn(`Skipped ${skipped.length} file(s) (already exist):`);
    for (const f of skipped) {
      logger.dim(`  ~ ${f}`);
    }
  }

  // If --deploy flag is set, also run the platform CLI
  const shouldDeploy = options?.deploy ?? false;
  const platformCli = PLATFORM_CLIS[target as DeployTarget];

  if (shouldDeploy && platformCli) {
    // Check CLI availability
    if (!isCliAvailable(platformCli.checkCmd)) {
      logger.error(`Platform CLI not found for ${target}.`);
      logger.dim(`Install it: ${platformCli.installHint}`);
      process.exit(1);
    }

    // Build first
    logger.info("Building app...");
    try {
      execSync("npx celsian build", { cwd, stdio: "inherit" });
    } catch {
      logger.error("Build failed. Fix build errors and try again.");
      process.exit(1);
    }

    // Deploy
    logger.info(`Deploying to ${target}...`);
    try {
      execSync(platformCli.deployCmd, { cwd, stdio: "inherit" });
      logger.success(`Deployed to ${target} successfully!`);
    } catch {
      logger.error(`Deployment to ${target} failed. Check the output above for details.`);
      process.exit(1);
    }
  } else {
    // Print next steps
    console.log("");
    printNextSteps(target as DeployTarget, false);
  }
}
