import { build } from 'esbuild';
import { rm } from 'node:fs/promises';

// Clean previous build
await rm('dist', { recursive: true, force: true });

await build({
  entryPoints: ['src/handler.ts'],
  outfile: 'dist/index.mjs',
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  minify: true,
  treeShaking: true,
  sourcemap: true,

  // Keep node built-ins external for smaller bundle size
  external: [
    'node:*',
    'crypto',
    'fs',
    'path',
    'os',
    'stream',
    'util',
    'events',
    'buffer',
    'http',
    'https',
    'net',
    'tls',
    'zlib',
    'querystring',
    'url',
  ],

  // Lambda uses .handler export from the file
  // ESM Lambda needs the file extension to be .mjs
  banner: {
    js: '// CelsianJS Lambda Bundle — generated by esbuild',
  },

  // Log build stats
  metafile: true,
});

console.log('Build complete: dist/index.mjs');
