// @celsian/cli, Deploy command tests

import { mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { type DeployTarget, getFilesForTarget } from "../src/commands/deploy.js";

const TMP_DIR = join(import.meta.dirname, ".tmp-deploy-test");

describe("getFilesForTarget", () => {
  describe("vercel", () => {
    it("returns api/index.ts and vercel.json", () => {
      const files = getFilesForTarget("vercel");
      const paths = files.map(([p]) => p);
      expect(paths).toEqual(["api/index.ts", "vercel.json"]);
    });

    it("api/index.ts content includes createVercelHandler", () => {
      const files = getFilesForTarget("vercel");
      const indexContent = files.find(([p]) => p === "api/index.ts")?.[1] ?? "";
      expect(indexContent).toContain("createVercelHandler");
    });

    it("api/index.ts content includes the generated-by comment", () => {
      const files = getFilesForTarget("vercel");
      const indexContent = files.find(([p]) => p === "api/index.ts")?.[1] ?? "";
      // The real flag is --platform (the old --target wording was a doc bug)
      expect(indexContent).toContain("Generated by: celsian deploy --platform vercel");
    });

    it("vercel.json contains rewrites config", () => {
      const files = getFilesForTarget("vercel");
      const jsonContent = files.find(([p]) => p === "vercel.json")?.[1] ?? "";
      const parsed = JSON.parse(jsonContent);
      expect(parsed.rewrites).toBeDefined();
      expect(parsed.rewrites[0].source).toBe("/api/(.*)");
    });
  });

  describe("lambda", () => {
    it("returns lambda.ts and template.yaml", () => {
      const files = getFilesForTarget("lambda");
      const paths = files.map(([p]) => p);
      expect(paths).toEqual(["lambda.ts", "template.yaml"]);
    });

    it("lambda.ts content includes createLambdaHandler", () => {
      const files = getFilesForTarget("lambda");
      const content = files.find(([p]) => p === "lambda.ts")?.[1] ?? "";
      expect(content).toContain("createLambdaHandler");
    });

    it("template.yaml includes SAM transform", () => {
      const files = getFilesForTarget("lambda");
      const content = files.find(([p]) => p === "template.yaml")?.[1] ?? "";
      expect(content).toContain("AWS::Serverless-2016-10-31");
    });
  });

  describe("cloudflare", () => {
    it("returns worker.ts and wrangler.toml", () => {
      const files = getFilesForTarget("cloudflare");
      const paths = files.map(([p]) => p);
      expect(paths).toEqual(["worker.ts", "wrangler.toml"]);
    });

    it("worker.ts content includes createCloudflareHandler", () => {
      const files = getFilesForTarget("cloudflare");
      const content = files.find(([p]) => p === "worker.ts")?.[1] ?? "";
      expect(content).toContain("createCloudflareHandler");
    });

    it("wrangler.toml includes compatibility_date", () => {
      const files = getFilesForTarget("cloudflare");
      const content = files.find(([p]) => p === "wrangler.toml")?.[1] ?? "";
      expect(content).toContain("compatibility_date");
    });
  });

  describe("fly", () => {
    it("returns Dockerfile, fly.toml, and .dockerignore", () => {
      const files = getFilesForTarget("fly");
      const paths = files.map(([p]) => p);
      expect(paths).toEqual(["Dockerfile", "fly.toml", ".dockerignore"]);
    });

    it("fly.toml includes health check config", () => {
      const files = getFilesForTarget("fly");
      const content = files.find(([p]) => p === "fly.toml")?.[1] ?? "";
      expect(content).toContain("/health");
      expect(content).toContain("http_service.checks");
    });
  });

  describe("railway", () => {
    it("returns Dockerfile, railway.json, and Procfile", () => {
      const files = getFilesForTarget("railway");
      const paths = files.map(([p]) => p);
      expect(paths).toEqual(["Dockerfile", "railway.json", "Procfile"]);
    });

    it("railway.json includes healthcheck config", () => {
      const files = getFilesForTarget("railway");
      const content = files.find(([p]) => p === "railway.json")?.[1] ?? "";
      const parsed = JSON.parse(content);
      expect(parsed.deploy.healthcheckPath).toBe("/health");
    });

    it("Procfile includes web process", () => {
      const files = getFilesForTarget("railway");
      const content = files.find(([p]) => p === "Procfile")?.[1] ?? "";
      expect(content).toContain("web:");
    });
  });

  describe("docker", () => {
    it("returns Dockerfile and .dockerignore", () => {
      const files = getFilesForTarget("docker");
      const paths = files.map(([p]) => p);
      expect(paths).toEqual(["Dockerfile", ".dockerignore"]);
    });

    it("Dockerfile uses multi-stage build", () => {
      const files = getFilesForTarget("docker");
      const content = files.find(([p]) => p === "Dockerfile")?.[1] ?? "";
      expect(content).toContain("AS builder");
      expect(content).toContain("FROM node:20-alpine");
    });

    it("Dockerfile runs as non-root user", () => {
      const files = getFilesForTarget("docker");
      const content = files.find(([p]) => p === "Dockerfile")?.[1] ?? "";
      expect(content).toContain("USER celsian");
    });

    it(".dockerignore excludes node_modules and .git", () => {
      const files = getFilesForTarget("docker");
      const content = files.find(([p]) => p === ".dockerignore")?.[1] ?? "";
      expect(content).toContain("node_modules");
      expect(content).toContain(".git");
    });
  });
});

describe("deployCommand file generation", () => {
  beforeEach(() => {
    mkdirSync(TMP_DIR, { recursive: true });
  });

  afterEach(() => {
    rmSync(TMP_DIR, { recursive: true, force: true });
  });

  it("all targets return non-empty file arrays", () => {
    const targets: DeployTarget[] = ["vercel", "lambda", "cloudflare", "fly", "railway", "docker"];
    for (const target of targets) {
      const files = getFilesForTarget(target);
      expect(files.length).toBeGreaterThan(0);
      for (const [path, content] of files) {
        expect(path.length).toBeGreaterThan(0);
        expect(content.length).toBeGreaterThan(0);
      }
    }
  });

  // Rewritten 2026-07-26. This used to assert the entrypoint imported
  // `@celsian/core`, which it did only because it built a brand-new EMPTY app
  // with `// TODO: Import your routes here`. Shipping that deployed a
  // health-check-only application. The entrypoint now imports the user's real
  // app, so the meaningful assertions are the adapter import and the app
  // import, and the absence of the TODO stub.
  it("serverless entrypoints import the user's app, not a fresh empty one", () => {
    const expectedAdapter: Record<string, string> = {
      vercel: "@celsian/adapter-vercel",
      lambda: "@celsian/adapter-lambda",
      cloudflare: "@celsian/adapter-cloudflare",
    };

    for (const target of ["vercel", "lambda", "cloudflare"] as DeployTarget[]) {
      const files = getFilesForTarget(target);
      const tsFile = files.find(([p]) => p.endsWith(".ts"));
      expect(tsFile, `${target}: no .ts entrypoint generated`).toBeDefined();
      const content = tsFile?.[1] ?? "";

      expect(content, `${target}: missing adapter import`).toContain(expectedAdapter[target]);
      // Imports the user's app from their source tree.
      expect(content, `${target}: does not import the user's app`).toMatch(/from\s+["'][./][^"']*src\/index\.js["']/);
      // The regression this guards: a stub app with no routes.
      expect(content, `${target}: still scaffolds an empty app`).not.toContain("TODO: Import your routes");
      expect(content, `${target}: still calls createApp()`).not.toContain("createApp(");
    }
  });

  it("container targets share the same Dockerfile content", () => {
    const flyDockerfile = getFilesForTarget("fly").find(([p]) => p === "Dockerfile")?.[1];
    const railwayDockerfile = getFilesForTarget("railway").find(([p]) => p === "Dockerfile")?.[1];
    const dockerDockerfile = getFilesForTarget("docker").find(([p]) => p === "Dockerfile")?.[1];
    expect(flyDockerfile).toBe(railwayDockerfile);
    expect(railwayDockerfile).toBe(dockerDockerfile);
  });
});
