// @celsian/adapter-fly — Deploy CelsianJS apps to Fly.io
//
// Fly.io supports:
// - Multi-region deployment (edge-close to users)
// - Machines API (auto-scaling)
// - Persistent volumes
// - Private networking (Fly WireGuard)
// - Built-in metrics and observability
//
// This adapter generates fly.toml, Dockerfile, and optional multi-region config.

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export interface FlyAdapterOptions {
  /** Fly.io app name (auto-generated if not set) */
  appName?: string;
  /** Primary region (default: 'iad' — Ashburn, VA) */
  primaryRegion?: string;
  /** Additional regions to deploy to */
  regions?: string[];
  /** Node.js version (default: '20') */
  nodeVersion?: string;
  /** Health check path (default: '/api/health') */
  healthCheckPath?: string;
  /** Health check interval in ms (default: 10000) */
  healthCheckInterval?: number;
  /** Memory per machine in MB (default: 256) */
  memoryMb?: number;
  /** CPU kind (default: 'shared') */
  cpuKind?: 'shared' | 'performance';
  /** Number of CPUs (default: 1) */
  cpus?: number;
  /** Auto-stop idle machines (default: true) */
  autoStop?: boolean;
  /** Auto-start on request (default: true) */
  autoStart?: boolean;
  /** Minimum machines to keep running (default: 0) */
  minMachines?: number;
}

export interface DeployAdapter {
  name: string;
  buildEnd(options: {
    serverEntry: string;
    clientDir: string;
    staticDir: string;
    outDir: string;
  }): Promise<void>;
}

/**
 * Create a Fly.io deployment adapter.
 *
 * Usage in then.config.ts:
 * ```ts
 * import { flyAdapter } from '@celsian/adapter-fly';
 *
 * export default defineConfig({
 *   build: {
 *     adapter: flyAdapter({
 *       appName: 'my-app',
 *       primaryRegion: 'iad',
 *       regions: ['lhr', 'nrt'],
 *     }),
 *   },
 * });
 * ```
 */
export function flyAdapter(options: FlyAdapterOptions = {}): DeployAdapter {
  const nodeVersion = options.nodeVersion ?? '20';
  const primaryRegion = options.primaryRegion ?? 'iad';
  const healthCheckPath = options.healthCheckPath ?? '/api/health';
  const healthCheckInterval = options.healthCheckInterval ?? 10_000;
  const memoryMb = options.memoryMb ?? 256;
  const cpuKind = options.cpuKind ?? 'shared';
  const cpus = options.cpus ?? 1;
  const autoStop = options.autoStop ?? true;
  const autoStart = options.autoStart ?? true;
  const minMachines = options.minMachines ?? 0;

  return {
    name: 'fly',

    async buildEnd({ outDir }) {
      // 1. Generate fly.toml
      const flyToml = generateFlyToml({
        appName: options.appName,
        primaryRegion,
        healthCheckPath,
        healthCheckInterval,
        memoryMb,
        cpuKind,
        cpus,
        autoStop,
        autoStart,
        minMachines,
      });
      await writeFile(join(outDir, 'fly.toml'), flyToml);

      // 2. Generate Dockerfile
      const dockerfile = generateFlyDockerfile(nodeVersion);
      await writeFile(join(outDir, 'Dockerfile'), dockerfile);

      // 3. Generate .dockerignore
      const dockerignore = [
        'node_modules',
        '.git',
        '.env',
        '.env.local',
        'src',
        '*.md',
        '.DS_Store',
        '',
      ].join('\n');
      await writeFile(join(outDir, '.dockerignore'), dockerignore);

      console.log('[celsian:adapter-fly] Generated deployment files:');
      console.log('  → fly.toml');
      console.log('  → Dockerfile');
      console.log('  → .dockerignore');
      if (options.regions?.length) {
        console.log(`  → Multi-region: ${primaryRegion} (primary), ${options.regions.join(', ')}`);
      }
    },
  };
}

function generateFlyToml(opts: {
  appName?: string;
  primaryRegion: string;
  healthCheckPath: string;
  healthCheckInterval: number;
  memoryMb: number;
  cpuKind: string;
  cpus: number;
  autoStop: boolean;
  autoStart: boolean;
  minMachines: number;
}): string {
  const lines: string[] = [
    '# CelsianJS — Fly.io Configuration',
    '# Generated by @celsian/adapter-fly',
    '',
  ];

  if (opts.appName) {
    lines.push(`app = '${opts.appName}'`);
  }
  lines.push(`primary_region = '${opts.primaryRegion}'`);
  lines.push('');

  // Build
  lines.push('[build]');
  lines.push('  dockerfile = "Dockerfile"');
  lines.push('');

  // Environment
  lines.push('[env]');
  lines.push("  NODE_ENV = 'production'");
  lines.push("  PORT = '3000'");
  lines.push("  HOST = '0.0.0.0'");
  lines.push('');

  // HTTP service
  lines.push('[http_service]');
  lines.push('  internal_port = 3000');
  lines.push('  force_https = true');
  lines.push('  auto_stop_machines = ' + (opts.autoStop ? 'true' : 'false'));
  lines.push('  auto_start_machines = ' + (opts.autoStart ? 'true' : 'false'));
  lines.push(`  min_machines_running = ${opts.minMachines}`);
  lines.push('');

  // Concurrency
  lines.push('  [http_service.concurrency]');
  lines.push('    type = "requests"');
  lines.push('    hard_limit = 250');
  lines.push('    soft_limit = 200');
  lines.push('');

  // Health check
  lines.push('[[http_service.checks]]');
  lines.push(`  grace_period = '10s'`);
  lines.push(`  interval = '${Math.round(opts.healthCheckInterval / 1000)}s'`);
  lines.push(`  method = 'GET'`);
  lines.push(`  path = '${opts.healthCheckPath}'`);
  lines.push(`  timeout = '5s'`);
  lines.push('');

  // Machine sizing
  lines.push('[[vm]]');
  lines.push(`  memory = '${opts.memoryMb}mb'`);
  lines.push(`  cpu_kind = '${opts.cpuKind}'`);
  lines.push(`  cpus = ${opts.cpus}`);
  lines.push('');

  return lines.join('\n');
}

function generateFlyDockerfile(nodeVersion: string): string {
  return `# CelsianJS — Fly.io Dockerfile
# Generated by @celsian/adapter-fly
# Deploy: flyctl deploy

FROM node:${nodeVersion}-alpine AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN \\
  if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile --prod; \\
  elif [ -f package-lock.json ]; then npm ci --production; \\
  else npm install --production; fi

# Production image
FROM base AS runner
ENV NODE_ENV=production

# Fly.io injects PORT at runtime
ENV PORT=3000
ENV HOST=0.0.0.0

# Don't run as root
RUN addgroup --system --gid 1001 celsian && \\
    adduser --system --uid 1001 celsian
USER celsian

COPY --from=deps --chown=celsian:celsian /app/node_modules ./node_modules
COPY --chown=celsian:celsian dist/ ./dist/

EXPOSE 3000

CMD ["node", "dist/server/entry.js"]
`;
}

export default flyAdapter;
