// @celsian/adapter-railway — Deploy CelsianJS apps to Railway
//
// Railway supports:
// - Automatic builds with Nixpacks (detects Node.js)
// - Custom Dockerfiles
// - Health checks
// - Environment variables
// - Private networking
//
// This adapter generates the deployment-specific files that Railway needs.

import { writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface RailwayAdapterOptions {
  /** Node.js version (default: '20') */
  nodeVersion?: string;
  /** Health check path (default: '/api/health') */
  healthCheckPath?: string;
  /** Enable Railway's restart policy (default: true) */
  restartPolicy?: boolean;
  /** Region hint — Railway handles this via dashboard but we document it */
  region?: string;
  /** Whether to generate a Dockerfile (default: false — let Nixpacks handle it) */
  dockerfile?: boolean;
}

export interface DeployAdapter {
  name: string;
  buildEnd(options: { serverEntry: string; clientDir: string; staticDir: string; outDir: string }): Promise<void>;
}

/**
 * Create a Railway deployment adapter.
 *
 * Usage in then.config.ts:
 * ```ts
 * import { railwayAdapter } from '@celsian/adapter-railway';
 *
 * export default defineConfig({
 *   build: {
 *     adapter: railwayAdapter({ healthCheckPath: '/api/health' }),
 *   },
 * });
 * ```
 */
export function railwayAdapter(options: RailwayAdapterOptions = {}): DeployAdapter {
  const nodeVersion = options.nodeVersion ?? "20";
  const healthCheckPath = options.healthCheckPath ?? "/api/health";
  const generateDockerfile = options.dockerfile ?? false;

  return {
    name: "railway",

    async buildEnd({ outDir }) {
      // 1. Generate Procfile — Railway uses this to start the app
      const procfile = `web: node dist/server/entry.js\n`;
      await writeFile(join(outDir, "Procfile"), procfile);

      // 2. Generate railway.json — deployment config
      const railwayConfig = {
        $schema: "https://railway.app/railway.schema.json",
        build: {
          builder: generateDockerfile ? "DOCKERFILE" : "NIXPACKS",
          nixpacksPlan: generateDockerfile
            ? undefined
            : {
                providers: ["node"],
                phases: {
                  setup: { nixPkgs: [`nodejs_${nodeVersion}`] },
                  install: { cmds: ["npm ci --production"] },
                },
              },
        },
        deploy: {
          startCommand: "node dist/server/entry.js",
          healthcheckPath: healthCheckPath,
          healthcheckTimeout: 10,
          restartPolicyType: options.restartPolicy !== false ? "ON_FAILURE" : "NEVER",
          restartPolicyMaxRetries: 3,
        },
      };

      await writeFile(join(outDir, "railway.json"), `${JSON.stringify(railwayConfig, null, 2)}\n`);

      // 3. Optionally generate Dockerfile
      if (generateDockerfile) {
        const dockerfile = generateRailwayDockerfile(nodeVersion);
        await writeFile(join(outDir, "Dockerfile"), dockerfile);
      }

      // 4. Generate .env.example for Railway env vars
      const envExample = [
        "# CelsianJS — Railway Environment Variables",
        "# These are automatically injected by Railway",
        "",
        "# Server",
        "PORT=3000",
        "HOST=0.0.0.0",
        "NODE_ENV=production",
        "",
        "# Railway provides these automatically:",
        "# RAILWAY_ENVIRONMENT",
        "# RAILWAY_GIT_COMMIT_SHA",
        "# RAILWAY_SERVICE_NAME",
        "",
      ].join("\n");

      await writeFile(join(outDir, ".env.example"), envExample);

      console.log("[celsian:adapter-railway] Generated deployment files:");
      console.log("  → Procfile");
      console.log("  → railway.json");
      if (generateDockerfile) console.log("  → Dockerfile");
      console.log("  → .env.example");
    },
  };
}

function generateRailwayDockerfile(nodeVersion: string): string {
  return `# CelsianJS — Railway Dockerfile
# Generated by @celsian/adapter-railway

FROM node:${nodeVersion}-alpine AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN \\
  if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile --prod; \\
  elif [ -f package-lock.json ]; then npm ci --production; \\
  else npm install --production; fi

# Production image
FROM base AS runner
ENV NODE_ENV=production
ENV PORT=3000
ENV HOST=0.0.0.0

COPY --from=deps /app/node_modules ./node_modules
COPY dist/ ./dist/

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
  CMD wget -qO- http://localhost:3000/api/health || exit 1

CMD ["node", "dist/server/entry.js"]
`;
}

export default railwayAdapter;
